CLAVE_CIFRADO = "$dCDRnVXdJNAdyk^"

CHUNK_SIZE = 128  # bytes

MINIMO_PALABRAS_CONJUNTO = 20


RANKING_SUPERVIVENCIA = "supervivencia"
RANKING_SUPERVIVENCIA_LENGUAJE = "supervivencia-lenguaje"
RANKING_PUNTAJES = "puntajes"
RANKING_PUNTAJES_LENGUAJE = "puntajes-lenguaje"
RANKING_ADICCION = "adiccion"
RANKING_VICTORIAS = "victorias"

RANKINGS = [
    RANKING_SUPERVIVENCIA,
    RANKING_SUPERVIVENCIA_LENGUAJE,
    RANKING_PUNTAJES,
    RANKING_PUNTAJES_LENGUAJE,
    RANKING_ADICCION,
    RANKING_VICTORIAS,
]

RANKINGS_WITH_GAME_SET = [
    RANKING_SUPERVIVENCIA_LENGUAJE,
    RANKING_PUNTAJES_LENGUAJE,
]


RANKING_TEXTS = {
    RANKING_SUPERVIVENCIA: "Supervivencia",
    RANKING_SUPERVIVENCIA_LENGUAJE: "Supervivencia por lenguaje",
    RANKING_PUNTAJES: "Puntajes",
    RANKING_PUNTAJES_LENGUAJE: "Puntajes por lenguaje",
    RANKING_ADICCION: "Adicción",
    RANKING_VICTORIAS: "Victorias",
}


MINIMO_ENTRADAS_CLASIFICACION = 10

CUSTOM = "personalizado"

VIDAS_INICIALES = 10
